#!/usr/bin/env bash
# Script that groups visitors by IP and HTTP status code.
#   Groups visitors by IP and HTTP status code.
#   display the number of occurrences, IP, and HTTP status
#   code of each log, in sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
